name: Execute automated checks
on:
  - push
jobs:
# https://github.com/golangci/golangci-lint-action#how-to-use
  lint:
    name: Lint go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Lint go code with golangci-lint
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.61.0
          args: --timeout=5m
  test:
    name: Verify go test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup golang
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: v1.61.0
      - name: Print go version
        run: go version
      - name: Execute go tests 
        run: go test -v ./...
  tilt-ci-dev:
    name: Verify tilt ci (development images)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced # v1.9.0
      - name: Install tilt & helm
        uses: yokawasa/action-setup-kube-tools@dc0754a9a47b40f22f9bd52ffb082bbe6d142b22 # v0.11.0
        with:
          setup-tools: |
            tilt
            helm
          tilt: 'v0.33.11'
          helm: 'v3.6.3'
      - name: Install helmfile
        run: |
          curl --fail -L -s --max-time 60 -o /usr/local/bin/helmfile https://github.com/roboll/helmfile/releases/download/v0.140.0/helmfile_linux_amd64
          chmod +x /usr/local/bin/helmfile
      - name: Install helm diff
        run: |
          helm plugin install https://github.com/databus23/helm-diff
      - name: Install dependencies
        run: |
          helmfile sync
      - name: Verify tilt ci
        run: |
          timeout 600 tilt ci
  tilt-ci-prod:
    name: Verify tilt ci (production images)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced # v1.9.0
      - name: Install tilt cli
        uses: yokawasa/action-setup-kube-tools@dc0754a9a47b40f22f9bd52ffb082bbe6d142b22 # v0.11.0
        with:
          setup-tools: |
            tilt
            helm
          tilt: 'v0.33.11'
          helm: 'v3.6.3'
      - name: Install helmfile
        run: |
          curl --fail -L -s --max-time 60 -o /usr/local/bin/helmfile https://github.com/roboll/helmfile/releases/download/v0.140.0/helmfile_linux_amd64
          chmod +x /usr/local/bin/helmfile
      - name: Install helm diff
        run: |
          helm plugin install https://github.com/databus23/helm-diff
      - name: Install dependencies
        run: |
          helmfile sync
      - name: Verify tilt ci
        run: |
          PROD=1 timeout 600 tilt ci
